from __future__ import annotations

import argparse
import hashlib
import importlib
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path


PACKAGE_ROOT = Path(__file__).resolve().parent.parent
PYTHON_ROOT = PACKAGE_ROOT / "python" / "src"
SOURCE_PREFIX = "packages/app/public/text-effect-catalog/components"
PROVENANCE_PREFIX = f"main-repository:{SOURCE_PREFIX}/"
STYLE = {
    "caption-blend-difference": ("difference", "caption", "MAKE THE CONTRAST WORK", "#ffffff", "#111111"),
    "caption-clip-wipe": ("wipe", "caption", "REVEAL EVERY WORD", "#ffffff", "#ff3155"),
    "caption-editorial-emphasis": ("editorial", "caption", "Make the key phrase matter", "#fff8ec", "#ffb45b"),
    "caption-emoji-pop": ("pop", "caption", "BIG MOMENT ✦", "#ffffff", "#ffcc33"),
    "caption-glitch-rgb": ("glitch", "caption", "SIGNAL INTERRUPTED", "#ffffff", "#ff285c"),
    "caption-gradient-fill": ("gradient", "caption", "COLOR MOVES WITH ENERGY", "#ffffff", "#8b5cf6"),
    "caption-highlight": ("highlight", "caption", "HIGHLIGHT THE ACTIVE IDEA", "#ffffff", "#e5153e"),
    "caption-kinetic-slam": ("slam", "caption", "IMPACT", "#ffffff", "#ff3b30"),
    "caption-matrix-decode": ("scramble", "caption", "DECODE THE MESSAGE", "#00ff41", "#00b82e"),
    "caption-neon-accent": ("glow", "caption", "NEON ACCENT", "#ffffff", "#ff3bd4"),
    "caption-neon-glow": ("glow", "caption", "GLOW THROUGH THE NOISE", "#65f6ff", "#ff4fe1"),
    "caption-parallax-layers": ("parallax", "caption", "DEPTH BEHIND THE SUBJECT", "#ffffff", "#675cff"),
    "caption-particle-burst": ("burst", "caption", "BURST ON THE BEAT", "#ffffff", "#ffb000"),
    "caption-pill-karaoke": ("pill", "caption", "FOLLOW EVERY WORD", "#ffffff", "#ecff4d"),
    "caption-texture": ("texture", "caption", "TACTILE TYPE", "#ffffff", "#ff7433"),
    "caption-weight-shift": ("weight", "caption", "Quiet words become strong", "#ffffff", "#a7b0c0"),
    "creed-kinetic-text": ("creed", "text", "ONE STEP AT A TIME", "#f6f3ea", "#9b765d"),
    "morph-text": ("morph", "text", "BUILT FOR WHAT'S NEXT", "#111111", "#737373"),
    "negative-face-follow": ("face-follow", "text", "RELENTLESS", "#ffffff", "#111111"),
    "shimmer-sweep": ("shimmer", "text", "PREMIUM REVEAL", "#d5b86c", "#fff5c2"),
    "texture-mask-text": ("texture-mask", "text", "CUT THROUGH", "#ffffff", "#8d8d8d"),
}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Import tracked VibeEdit text designs into the portable motion runtime")
    parser.add_argument("--source-root", type=Path, required=True)
    parser.add_argument("--revision", default="HEAD")
    args = parser.parse_args(argv)
    root = args.source_root.resolve()
    revision = _git(root, "rev-parse", args.revision).decode().strip()
    components = _registry_components(root, revision) + _mogrt_components(root, revision)
    if len(components) != 74:
        raise RuntimeError(f"reviewed portable text inventory changed: expected 74, found {len(components)}")
    if len({component["id"] for component in components}) != len(components):
        raise RuntimeError("portable text identifiers must be unique")

    manifest = {"schemaVersion": "1.0.0", "revision": revision, "components": components}
    (PACKAGE_ROOT / "catalog" / "motion-components.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    (PACKAGE_ROOT / "src" / "motion" / "components.generated.js").write_text(
        "// Generated by scripts/import_text_components.py from a tracked VibeEdit revision.\n"
        f"export const portableMotionComponents = Object.freeze({json.dumps(components, separators=(',', ':'), ensure_ascii=False)});\n",
        encoding="utf-8",
    )
    validation = _validate(components, revision)
    (PACKAGE_ROOT / "catalog" / "motion-validation.json").write_text(
        json.dumps(validation, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    _write_catalog(components)
    print(json.dumps({"ok": True, "revision": revision, "components": len(components), "families": validation["families"], "aggregateSha256": validation["aggregateSha256"]}))
    return 0


def _registry_components(root: Path, revision: str) -> list[dict]:
    paths = _git(root, "ls-tree", "-r", "--name-only", revision, SOURCE_PREFIX).decode().splitlines()
    registry_paths = sorted(path for path in paths if path.count("/") == SOURCE_PREFIX.count("/") + 2 and path.endswith("/registry-item.json"))
    components = []
    for path in registry_paths:
        metadata_bytes = _show(root, revision, path)
        metadata = json.loads(metadata_bytes)
        name = metadata["name"]
        if name in {"html-motion-mogrt", "learned-text-styles"}:
            continue
        if name not in STYLE:
            raise RuntimeError(f"portable style mapping missing for {name}")
        html_entry = next((item["path"] for item in metadata["files"] if item["path"].endswith(".html")), None)
        if not html_entry:
            raise RuntimeError(f"tracked component has no HTML source: {name}")
        html_path = f"{SOURCE_PREFIX}/{name}/{html_entry}"
        source_hash = hashlib.sha256(metadata_bytes + b"\0" + _show(root, revision, html_path)).hexdigest()
        motion, kind, default_text, foreground, accent = STYLE[name]
        components.append(
            {
                "id": f"vibeedit://text/{name}",
                "name": metadata["title"],
                "description": metadata["description"],
                "kind": kind,
                "family": "portable-catalog",
                "motion": motion,
                "defaultText": default_text,
                "palette": {"foreground": foreground, "accent": accent},
                "tags": list(dict.fromkeys([*metadata.get("tags", []), "portable", "deterministic"])),
                "source": {"path": html_path, "registryPath": path, "revision": revision, "sha256": source_hash},
            }
        )
    return components


def _mogrt_components(root: Path, revision: str) -> list[dict]:
    prefix = f"{SOURCE_PREFIX}/html-motion-mogrt/configs"
    paths = sorted(path for path in _git(root, "ls-tree", "-r", "--name-only", revision, prefix).decode().splitlines() if path.endswith(".json"))
    components = []
    for path in paths:
        source = _show(root, revision, path)
        config = json.loads(source)
        slug = config["slug"]
        family = config["family"]
        default_text = _default_text(config) or slug.replace("_", " ")
        foreground, accent = _palette(config, family)
        components.append(
            {
                "id": f"vibeedit://text/mogrt-{_slug(slug)}",
                "name": config.get("name", slug.replace("_", " ").title()),
                "description": f"Portable deterministic {family.replace('-', ' ')} adaptation of the tracked VibeEdit {slug} motion-title configuration.",
                "kind": "text",
                "family": family,
                "motion": _family_motion(family, slug),
                "defaultText": default_text,
                "palette": {"foreground": foreground, "accent": accent},
                "tags": ["text", "motion-title", "mogrt-adaptation", family, "portable", "deterministic"],
                "source": {"path": path, "revision": revision, "sha256": hashlib.sha256(source).hexdigest()},
            }
        )
    return components


def _validate(components: list[dict], revision: str) -> dict:
    node = shutil.which("node")
    if not node:
        raise RuntimeError("Node.js is required to validate generated text components")
    node_script = """
import { createHash } from 'node:crypto';
import { portableMotionComponents, renderComponent } from './src/index.js';
const digest = createHash('sha256');
for (const component of portableMotionComponents) {
  const context = { durationFrames: 60, width: 640, height: 360 };
  const early = renderComponent(component.id, {}, 2, context);
  const late = renderComponent(component.id, {}, 42, context);
  if (early !== renderComponent(component.id, {}, 2, context) || early === late || !early.includes('data-vibeedit-component=')) throw new Error(component.id);
  digest.update(component.id); digest.update(early); digest.update(late);
}
console.log(JSON.stringify({ count: portableMotionComponents.length, sha256: digest.digest('hex') }));
"""
    result = subprocess.run([node, "--input-type=module", "-e", node_script], cwd=PACKAGE_ROOT, capture_output=True, text=True, check=False)
    if result.returncode:
        raise RuntimeError(result.stderr.strip() or "JavaScript motion validation failed")
    node_result = json.loads(result.stdout)

    sys.path.insert(0, str(PYTHON_ROOT))
    importlib.invalidate_caches()
    for name in tuple(sys.modules):
        if name == "vibeedit.motion":
            del sys.modules[name]
    motion = importlib.import_module("vibeedit.motion")
    digest = hashlib.sha256()
    for component in motion.list_motion_components():
        spec = _test_spec(component["id"])
        early = motion.document_for_frame(spec, 2)
        late = motion.document_for_frame(spec, 42)
        if early != motion.document_for_frame(spec, 2) or early == late or "data-vibeedit-component=" not in early:
            raise RuntimeError(f"Python motion validation failed: {component['id']}")
        digest.update(component["id"].encode())
        digest.update(early.encode())
        digest.update(late.encode())
    families = {}
    for component in components:
        families[component["family"]] = families.get(component["family"], 0) + 1
    return {
        "schemaVersion": "1.0.0",
        "status": "passed",
        "revision": revision,
        "cases": len(components),
        "families": dict(sorted(families.items())),
        "runtime": {"python": sys.version.split()[0], "node": subprocess.run([node, "--version"], capture_output=True, text=True, check=True).stdout.strip()},
        "javascriptSha256": node_result["sha256"],
        "pythonSha256": digest.hexdigest(),
        "aggregateSha256": hashlib.sha256(f"{node_result['sha256']}:{digest.hexdigest()}".encode()).hexdigest(),
        "contract": "Every generated component rendered deterministically at two integer frames in both public runtimes without network or binary assets.",
    }


def _write_catalog(components: list[dict]) -> None:
    path = PACKAGE_ROOT / "catalog" / "catalog.json"
    catalog = json.loads(path.read_text(encoding="utf-8"))
    retained = [item for item in catalog["items"] if not item.get("provenance", {}).get("source", "").startswith(PROVENANCE_PREFIX) and item["id"] != "vibeedit://template/portable-motion-showcase"]
    catalog["items"] = retained + [_catalog_item(component) for component in components] + [_showcase_item()]
    path.write_text(json.dumps(catalog, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def _catalog_item(component: dict) -> dict:
    identifier = component["id"]
    mogrt = "/html-motion-mogrt/" in component["source"]["path"]
    return {
        "id": identifier,
        "name": component["name"],
        "description": component["description"],
        "category": "text",
        "tags": component["tags"],
        "version": "0.1.0",
        "inputs": {"text": True},
        "parameters": {
            "type": "object",
            "properties": {
                "text": {"type": "string", "default": component["defaultText"]},
                "foreground": {"type": "string", "default": component["palette"]["foreground"]},
                "accent": {"type": "string", "default": component["palette"]["accent"]},
                "background": {"type": "string", "default": "transparent"},
            },
            "additionalProperties": False,
        },
        "platforms": ["macos", "windows", "linux"],
        "backends": ["html", "chromium"],
        "preview": {"status": "missing", "note": "Both seekable runtimes pass; a release preview has not yet been generated for this component."},
        "examples": {
            "python": f"MotionComponent('title', Placement(0, 60), {identifier!r}, {{'text': {component['defaultText']!r}}})",
            "javascript": f"renderComponent({identifier!r}, {{ text: {component['defaultText']!r} }}, 12, {{ durationFrames: 60, width: 640, height: 360 }})",
        },
        "prompts": [f"Use {component['name']} for this text and keep the motion frame-seekable and transparent.", f"Adapt the wording and palette while preserving the {component['motion']} motion grammar."],
        "requirements": {"assets": [], "models": []},
        "license": {
            "owner": "Attention Engine Inc.",
            "terms": "SEE LICENSE IN LICENSE.md",
            "redistribution": "verified",
            "notes": "Portable VibeEdit-owned adaptation only; source fonts, textures, CDNs, MOGRT binaries, and remote previews are not bundled.",
        },
        "provenance": {
            "kind": "adapted",
            "source": f"main-repository:{component['source']['path']}#revision={component['source']['revision']}&sha256={component['source']['sha256']}",
            "implementation": "src/motion/runtime.js",
            "thirdParty": ["Original MOGRT design reference (not bundled)"] if mogrt else [],
        },
        "validation": [
            {
                "id": "cross-runtime-seek",
                "status": "passed",
                "command": "node --test test/motion-catalog.test.js && pytest python/tests/test_motion_catalog.py",
                "evidence": "Deterministic early/late integer-frame rendering passed in JavaScript and Python with no network dependency.",
            }
        ],
    }


def _showcase_item() -> dict:
    return {
        "id": "vibeedit://template/portable-motion-showcase",
        "name": "Portable Motion Showcase",
        "description": "Executable source-video template proving a tracked MOGRT adaptation and a portable caption style through deterministic Chromium rendering.",
        "category": "template",
        "tags": ["motion", "text", "caption", "chromium", "executable"],
        "version": "0.1.0",
        "inputs": {"media": ["video", "audio"], "minimumClips": 1},
        "parameters": {"type": "object", "properties": {"title": {"type": "string", "default": "PORTABLE MOTION"}, "caption": {"type": "string", "default": "SEEK EVERY FRAME"}}, "additionalProperties": False},
        "platforms": ["macos", "windows", "linux"],
        "backends": ["python", "html", "chromium", "ffmpeg"],
        "preview": {"status": "missing", "note": "Run the preview builder to create the verified local render."},
        "examples": {"python": "create_example('portable-motion-showcase')", "javascript": "createExample('portable-motion-showcase')"},
        "prompts": ["Start from the portable motion showcase, replace the source, and preserve integer-frame text timing."],
        "requirements": {"assets": [], "models": []},
        "license": {"owner": "Attention Engine Inc.", "terms": "SEE LICENSE IN LICENSE.md", "redistribution": "verified"},
        "provenance": {"kind": "vibeedit-owned", "source": "release-package portable motion integration", "implementation": "examples/portable-motion-showcase/composition.json", "thirdParty": ["FFmpeg", "Playwright", "Chromium"]},
        "validation": [{"id": "end-to-end", "status": "passed", "command": "python examples/portable-motion-showcase/render.py", "evidence": "Source video/audio plus two portable HTML motion components render to a frame-accurate verified MP4."}],
    }


def _test_spec(identifier: str) -> dict:
    return {
        "canvas": {"width": 640, "height": 360},
        "timeline": {"tracks": [{"order": 0, "items": [{"id": "motion", "kind": "motion", "placement": {"startFrame": 0, "durationFrames": 60}, "componentId": identifier, "props": {}}]}]},
    }


def _default_text(config: dict) -> str:
    candidates = [config.get("text"), config.get("recipe", {}).get("text") if isinstance(config.get("recipe"), dict) else None]
    recipe = config.get("recipe") if isinstance(config.get("recipe"), dict) else {}
    for key in ("texts", "crossing_texts"):
        if isinstance(recipe.get(key), list):
            candidates.append(" ".join(str(item.get("text", "")) for item in recipe[key] if isinstance(item, dict)))
    if isinstance(config.get("controls"), list):
        candidates.extend(item.get("value") for item in config["controls"] if item.get("type") == 6)
    return next((str(value).replace("\r", " ").replace("\n", " ").strip() for value in candidates if isinstance(value, str) and value.strip()), "")


def _palette(config: dict, family: str) -> tuple[str, str]:
    values = []

    def visit(value, key=""):
        if isinstance(value, dict):
            for child_key, child in value.items():
                visit(child, child_key.casefold())
            return
        if isinstance(value, list):
            if any(token in key for token in ("color", "fill", "top", "bottom", "glow", "highlight")) and len(value) in {3, 4} and all(isinstance(item, (int, float)) for item in value):
                scale = 255 if max(value) <= 1 else 1
                values.append("#" + "".join(f"{max(0, min(255, round(item * scale))):02x}" for item in value[:3]))
            for child in value:
                visit(child, key)

    visit(config)
    defaults = {
        "aesthetic-glow": ("#f6f0df", "#b026ff"),
        "apple-clean": ("#ffffff", "#8ca8ff"),
        "dimensional-metal": ("#e6e6e6", "#de3131"),
        "analog-glitch": ("#ffffff", "#ff285c"),
        "rainbow-trippy": ("#ffffff", "#d44bff"),
        "water-warp": ("#e8fbff", "#319dc7"),
        "elegant-misc": ("#fff7e6", "#b99152"),
        "simple-motion": ("#ffffff", "#7d8ea8"),
    }.get(family, ("#ffffff", "#808080"))
    return (values[0] if values else defaults[0], values[1] if len(values) > 1 else defaults[1])


def _family_motion(family: str, slug: str) -> str:
    if "GLITCH" in slug or "VHS" in slug or family == "analog-glitch":
        return "glitch"
    if family == "aesthetic-glow":
        return "glow"
    if family == "dimensional-metal":
        return "creed"
    if family == "rainbow-trippy":
        return "gradient"
    if family == "water-warp":
        return "morph"
    if "ZOOM" in slug or "REBOUND" in slug or "BOUNCE" in slug:
        return "pop"
    if any(token in slug for token in ("LEFT", "RIGHT", "ABOVE", "BOTTOM")):
        return "wipe"
    return "rise"


def _slug(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", value.casefold()).strip("-")


def _show(root: Path, revision: str, path: str) -> bytes:
    return _git(root, "show", f"{revision}:{path}")


def _git(root: Path, *args: str) -> bytes:
    result = subprocess.run(["git", "-C", str(root), *args], capture_output=True, check=False)
    if result.returncode:
        raise RuntimeError(result.stderr.decode(errors="replace").strip() or f"git {' '.join(args)} failed")
    return result.stdout


if __name__ == "__main__":
    raise SystemExit(main())
